/**
 * Freezes the built index.html into a module the serverless renderer can
 * import.
 *
 * The renderer needs the exact shell Vite produced — same hashed asset URLs,
 * same base tags — because it serves that HTML with per-route metadata
 * injected into it. Reading dist/index.html from inside the function at
 * runtime would mean depending on Vercel's file-inclusion behaviour and on
 * the function's working directory. Emitting a module instead makes the
 * dependency explicit and the bundle self-contained.
 *
 * Runs after `vite build`. dist/ is committed in this repo, and so is the
 * generated file, so the two never disagree.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(resolve(root, 'dist/index.html'), 'utf8');

const out = `// GENERATED by scripts/buildShell.mjs — do not edit by hand.
// Rebuilt on every \`npm run build\`; committed so dist/ and the renderer
// can never drift apart.
export const SHELL = ${JSON.stringify(html)};
`;

writeFileSync(resolve(root, 'api/_shell.js'), out);
console.log(`buildShell: api/_shell.js written (${html.length} bytes of shell)`);
